version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/install_git.sh
      timeout: 300
      runas: root
  Install:
    - location: scripts/install_awslogs.sh
      timeout: 300
      runas: root
    - location: scripts/install_metrics.sh
      timeout: 300
      runas: root
